# Generated by Django 4.2.5 on 2023-10-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_commerce_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_category",
            field=models.CharField(default="none", max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(default="none", upload_to="e_commerce_app/images"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_sub_category",
            field=models.CharField(default="none", max_length=70),
            preserve_default=False,
        ),
    ]
