# Generated by Django 4.2.5 on 2023-10-05 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("e_commerce_app", "0003_userprofile_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
